# MOTOR STATUS를 반복 조회하여 IDLE이 될 때까지 대기
# break문 사용 불가하므로 wait_done 임시 변수 사용

wait_done = 0

while wait_done == 0:
  socket_send_string(CMD_MOTOR_STATUS)
  global pc_response = socket_read_line()

  if pc_response == RESP_MOTOR_BUSY:
    global motor_state = 1
    sleep(0.1)

  elif pc_response == RESP_MOTOR_IDLE:
    global motor_state = 0
    global fail_flag = 0
    global wait_done = 1

  else:
    global fail_flag = 1
    global wait_done = 1
  end
end